$('#Tree1').click(function(){
        $('#Tree1').hide();
    });
$('#Tree2').click(function(){
        $('#Tree2').hide();
    });
$('#Tree3').click(function(){
        $('#Tree3').hide();
    });
$('#Tree4').click(function(){
        $('#Tree4').hide();
    });
$('#Tree5').click(function(){
        $('#Tree5').hide();
    });
